<?php

// autoload-classmap.php @generated by Strauss

$lib = dirname(__FILE__);

return array(
   'GravityWP\GravityWP_Addon_Name\Appsero\Client' => $lib . '/appsero/client/src/Client.php',
   'GravityWP\GravityWP_Addon_Name\Appsero\Insights' => $lib . '/appsero/client/src/Insights.php',
   'GravityWP\GravityWP_Addon_Name\Appsero\License' => $lib . '/appsero/client/src/License.php',
   'GravityWP\GravityWP_Addon_Name\Appsero\Updater' => $lib . '/appsero/client/src/Updater.php',
   'GravityWP\GravityWP_Addon_Name\GravityWP\LicenseHandler\LicenseHandler' => $lib . '/gravitywp/license-handler/src/LicenseHandler.php',
);